### PR TITLE
Fix edit_zone so that it will use a serial when one is provided.

### PR DESCRIPTION
**Pull request by ShaunR**
This looked like a bug to me. edit_zone was overwriting the serial when one was present.

We use the edit_zone api function to sync our local zones with NicTool. We check NicTool's serial to see if it matches our local version.  if it does not we update that zone and its records.  Since this function was not updating NicTool with our local serial this would cause the script to always think the zone had changed.

### CODE REVIEW

**Comment by msimerson** [comment]
That looks right. If you'll be so kind as to add a test for this, I'll merge it right away. Otherwise, it'll wait until I get around to wrapping that code in a test. (it's the best way to avoid regressions).

**Comment by ShaunR** [comment]
So it looks like there's already a test for edit_zone and it specifies a serial of 2.  The issue is that the test does a get_zone right after and checks to see if the serial is equal to 3.  The test expects the serial to increment.

So, do we fix this test and make sure the serial ends up being 2 and then duplicate the test with no serial to see if it increments?

Line 646 of 10_zones.t

**Comment by msimerson** [comment]
> The test expects the serial to increment.

They do indeed.  I also expect the serial number to **always** get incremented. By default, NicToolClient does not send the serial number in edit requests. It trusts the server to look up the current serial and increment it. That part works properly. The question is then, what exactly to do when the client does specify the serial? (save as-is, or increment?)

In this PR, you don't increment a client supplied serial, and thus the test mismatch.

Since more than one person can be editing a zone in NicTool, permitting the client to set the serial is potentially hazardous. If the client increments it backwards and BIND doesn't publish their zone changes, someone is likely to be surprised. I almost feel like if you set the serial you should get a big orange warning that you're running with scissors.

Perhaps a middle ground is to move this line:

```perl
$data->{serial} = $self->bump_serial( $data->{nt_zone_id}, $data->{serial} );
```

back outside the conditional so that the supplied serial is bumped?  That solves the test issue and if you really really must set the value to say, 4, then you'd just pass in a value of 3, knowing it'll get incremented.

This raises another question. Should we compare the new value to the previous value and reject the request if it decrements or fails to increment the serial in a BIND compatible way?

**Comment by ShaunR** [comment]
If you look at the new_zone function it allows setting a serial and if the serial is blank it bumps it.  I think edit_zone should do the same.

I'm using the API so the client interface can stay the same, as far as i know the client interface now doesn't give a user the option to modify a zones serial.  It can remain that way if you want and we can avoid the warnings.

As far as I know bind doesn't care if the serial went up or down. All it cares is that it changed.  At least that has been my experience with it.

We set the serial because were importing/syncing zones/records from many bind servers. Our script checks nictool for the zone, and then compares the serial with the local version.  If they don't match it knows the zone and/or records have changed and that they need to be re-synced.

**Comment by ShaunR** [comment]
Oh also, the system automatically bumps the serial for a zone when a record is added or edited. So really if somebody set's a serial and then modifies any of the records... the serial bumps again.

**Comment by msimerson** [comment]
> As far as I know bind doesn't care if the serial went up or down. All it cares is that it changed.

This is not the case for those using zone transfers (for at least *some*, if not all versions of BIND).

It sounds like if you simply adjust your syncing system to specify the (serial - 1) when saving zone edits to NicTool, then the serial incrementing can be left always enabled, right?

PS: There's quite a few NicTool API users and it seems likely that some have been setting the serial (some even accidentally in a foreach) number in their API requests for many years and serial bumping has continued to work The Right Way for them. After this change, not incrementing the serial after an edit may prove surprising and problematic.

> Oh also, the system automatically bumps the serial for a zone when a record is added or edited. So really if somebody set's a serial and then modifies any of the records... the serial bumps again.

That's the way it's supposed to work! If someone edits only a zone property (SOA, or one of the time values), the zone should get published with the new values.

**Comment by msimerson** [comment]
I have modified Zone.pm such that when a request contains a serial, it will get used. However, that value included will get incremented, as that provides behavior that's unlikely to harm existing users of the API.

**Comment by ShaunR** [comment]
Honestly i feel like were just making what was a bug worse just because we want to keep possible issues with people who were using the system improperly to begin with from having issues.  A change log entry notifying users of this change should be good enough.

The issue with me setting a serial - 1 is that the bump serial system doesn't just work with normal numbers.  It's assuming a YYYYMMDDRR format and if you start trying to -1 that you are going to end up with weird numbers and will no longer be in the correct format.  This means I now need to figure out/build a custom serial.

I do not understand why anybody would provide nictool with a serial just so nictool can change it.  It just does not make any sense.

If your really set on leaving it this way, maybe we can add a extra param called force_serial or something that will not bump it.

**Comment by msimerson** [comment]
> Honestly i feel like were just making what was a bug worse

Sorry, but I just don't agree. The API documents that one can provide a serial number in the edit request, therefore it's now honored. However, NicTool is nearly **always** used as the Source of Truth for an organizations DNS data. Whenever changes are made to the zone or it's data, the serial needs to increase.

> It's assuming a YYYYMMDDRR format

No, it doesn't assume. It evaluates the serial and increments it correctly based on its type. You choose the format.

> This means I now need to figure out/build a custom serial

If you're managing zones outside of NicTool, shouldn't you be doing that anyway?

Matt

**Comment by ShaunR** [comment]
No, why would i, the zone has a perfectly usable serial to begin with.

What do you think about adding another property like force_serial to do what I want?

**Comment by msimerson** [comment]
I don't like changing the API to add force_serial. I'm still considering the "when a zone serial is provided to edit_zone, don't increment it" idea. For now, just move that increment line outside into the conditional block and it'll do what you want.

When I get time I'll review a few of the API clients (I've written a dozen or so) and attempt to quantify the likelihood of any negative consequences.

**Comment by ShaunR** [comment]
OK, that sounds OK for now. I'm not trying to be a pain in the butt with this. I just feel like when you interface with the API your not a standard user, your hopefully a developer, and when you provide an API with data it shouldn't manipulate it. :)

**Pull request closed without merging**
